# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mujoco_ar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmujoco_ar.proto\x12\tmujoco_ar\"L\n\x10HandshakeRequest\x12\x10\n\x08usdz_url\x18\x01 \x01(\t\x12\x12\n\nmodel_name\x18\x02 \x01(\t\x12\x12\n\nnum_bodies\x18\x03 \x01(\x05\"5\n\x11HandshakeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\xae\x01\n\x11PoseUpdateRequest\x12?\n\nbody_poses\x18\x01 \x03(\x0b\x32+.mujoco_ar.PoseUpdateRequest.BodyPosesEntry\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x1a\x45\n\x0e\x42odyPosesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\"\n\x05value\x18\x02 \x01(\x0b\x32\x13.mujoco_ar.BodyPose:\x02\x38\x01\"6\n\x12PoseUpdateResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"Y\n\x08\x42odyPose\x12$\n\x08position\x18\x01 \x01(\x0b\x32\x12.mujoco_ar.Vector3\x12\'\n\x08rotation\x18\x02 \x01(\x0b\x32\x15.mujoco_ar.Quaternion\"*\n\x07Vector3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"8\n\nQuaternion\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\x32\xff\x01\n\x0fMuJoCoARService\x12J\n\rSendHandshake\x12\x1b.mujoco_ar.HandshakeRequest\x1a\x1c.mujoco_ar.HandshakeResponse\x12T\n\x11StreamPoseUpdates\x12\x1c.mujoco_ar.PoseUpdateRequest\x1a\x1d.mujoco_ar.PoseUpdateResponse(\x01\x30\x01\x12J\n\x0bUpdatePoses\x12\x1c.mujoco_ar.PoseUpdateRequest\x1a\x1d.mujoco_ar.PoseUpdateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mujoco_ar_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSEUPDATEREQUEST_BODYPOSESENTRY._options = None
  _POSEUPDATEREQUEST_BODYPOSESENTRY._serialized_options = b'8\001'
  _globals['_HANDSHAKEREQUEST']._serialized_start=30
  _globals['_HANDSHAKEREQUEST']._serialized_end=106
  _globals['_HANDSHAKERESPONSE']._serialized_start=108
  _globals['_HANDSHAKERESPONSE']._serialized_end=161
  _globals['_POSEUPDATEREQUEST']._serialized_start=164
  _globals['_POSEUPDATEREQUEST']._serialized_end=338
  _globals['_POSEUPDATEREQUEST_BODYPOSESENTRY']._serialized_start=269
  _globals['_POSEUPDATEREQUEST_BODYPOSESENTRY']._serialized_end=338
  _globals['_POSEUPDATERESPONSE']._serialized_start=340
  _globals['_POSEUPDATERESPONSE']._serialized_end=394
  _globals['_BODYPOSE']._serialized_start=396
  _globals['_BODYPOSE']._serialized_end=485
  _globals['_VECTOR3']._serialized_start=487
  _globals['_VECTOR3']._serialized_end=529
  _globals['_QUATERNION']._serialized_start=531
  _globals['_QUATERNION']._serialized_end=587
  _globals['_MUJOCOARSERVICE']._serialized_start=590
  _globals['_MUJOCOARSERVICE']._serialized_end=845
# @@protoc_insertion_point(module_scope)
