# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mujoco_ar_pb2 as mujoco__ar__pb2


class MuJoCoARServiceStub(object):
    """Service for communication between MuJoCo Python wrapper and VisionPro AR app
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendHandshake = channel.unary_unary(
                '/mujoco_ar.MuJoCoARService/SendHandshake',
                request_serializer=mujoco__ar__pb2.HandshakeRequest.SerializeToString,
                response_deserializer=mujoco__ar__pb2.HandshakeResponse.FromString,
                )
        self.StreamPoseUpdates = channel.stream_stream(
                '/mujoco_ar.MuJoCoARService/StreamPoseUpdates',
                request_serializer=mujoco__ar__pb2.PoseUpdateRequest.SerializeToString,
                response_deserializer=mujoco__ar__pb2.PoseUpdateResponse.FromString,
                )
        self.UpdatePoses = channel.unary_unary(
                '/mujoco_ar.MuJoCoARService/UpdatePoses',
                request_serializer=mujoco__ar__pb2.PoseUpdateRequest.SerializeToString,
                response_deserializer=mujoco__ar__pb2.PoseUpdateResponse.FromString,
                )


class MuJoCoARServiceServicer(object):
    """Service for communication between MuJoCo Python wrapper and VisionPro AR app
    """

    def SendHandshake(self, request, context):
        """Send initial handshake with USDZ URL
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamPoseUpdates(self, request_iterator, context):
        """Stream pose updates from MuJoCo simulation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePoses(self, request, context):
        """Send single pose update
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MuJoCoARServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendHandshake': grpc.unary_unary_rpc_method_handler(
                    servicer.SendHandshake,
                    request_deserializer=mujoco__ar__pb2.HandshakeRequest.FromString,
                    response_serializer=mujoco__ar__pb2.HandshakeResponse.SerializeToString,
            ),
            'StreamPoseUpdates': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamPoseUpdates,
                    request_deserializer=mujoco__ar__pb2.PoseUpdateRequest.FromString,
                    response_serializer=mujoco__ar__pb2.PoseUpdateResponse.SerializeToString,
            ),
            'UpdatePoses': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePoses,
                    request_deserializer=mujoco__ar__pb2.PoseUpdateRequest.FromString,
                    response_serializer=mujoco__ar__pb2.PoseUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mujoco_ar.MuJoCoARService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MuJoCoARService(object):
    """Service for communication between MuJoCo Python wrapper and VisionPro AR app
    """

    @staticmethod
    def SendHandshake(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mujoco_ar.MuJoCoARService/SendHandshake',
            mujoco__ar__pb2.HandshakeRequest.SerializeToString,
            mujoco__ar__pb2.HandshakeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamPoseUpdates(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/mujoco_ar.MuJoCoARService/StreamPoseUpdates',
            mujoco__ar__pb2.PoseUpdateRequest.SerializeToString,
            mujoco__ar__pb2.PoseUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatePoses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mujoco_ar.MuJoCoARService/UpdatePoses',
            mujoco__ar__pb2.PoseUpdateRequest.SerializeToString,
            mujoco__ar__pb2.PoseUpdateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
