// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: mujoco_ar.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - mujoco_ar.MuJoCoARService

/// Namespace containing generated types for the "mujoco_ar.MuJoCoARService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum MujocoAr_MuJoCoARService {
    /// Service descriptor for the "mujoco_ar.MuJoCoARService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "mujoco_ar.MuJoCoARService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "SendUsdzUrl" metadata.
        public enum SendUsdzUrl {
            /// Request type for "SendUsdzUrl".
            public typealias Input = MujocoAr_UsdzUrlRequest
            /// Response type for "SendUsdzUrl".
            public typealias Output = MujocoAr_UsdzUrlResponse
            /// Descriptor for "SendUsdzUrl".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mujoco_ar.MuJoCoARService"),
                method: "SendUsdzUrl"
            )
        }
        /// Namespace for "SendUsdzData" metadata.
        public enum SendUsdzData {
            /// Request type for "SendUsdzData".
            public typealias Input = MujocoAr_UsdzDataRequest
            /// Response type for "SendUsdzData".
            public typealias Output = MujocoAr_UsdzDataResponse
            /// Descriptor for "SendUsdzData".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mujoco_ar.MuJoCoARService"),
                method: "SendUsdzData"
            )
        }
        /// Namespace for "SendUsdzDataChunked" metadata.
        public enum SendUsdzDataChunked {
            /// Request type for "SendUsdzDataChunked".
            public typealias Input = MujocoAr_UsdzChunkRequest
            /// Response type for "SendUsdzDataChunked".
            public typealias Output = MujocoAr_UsdzDataResponse
            /// Descriptor for "SendUsdzDataChunked".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mujoco_ar.MuJoCoARService"),
                method: "SendUsdzDataChunked"
            )
        }
        /// Namespace for "StreamPoses" metadata.
        public enum StreamPoses {
            /// Request type for "StreamPoses".
            public typealias Input = MujocoAr_PoseUpdateRequest
            /// Response type for "StreamPoses".
            public typealias Output = MujocoAr_PoseUpdateResponse
            /// Descriptor for "StreamPoses".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mujoco_ar.MuJoCoARService"),
                method: "StreamPoses"
            )
        }
        /// Namespace for "UpdatePoses" metadata.
        public enum UpdatePoses {
            /// Request type for "UpdatePoses".
            public typealias Input = MujocoAr_PoseUpdateRequest
            /// Response type for "UpdatePoses".
            public typealias Output = MujocoAr_PoseUpdateResponse
            /// Descriptor for "UpdatePoses".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mujoco_ar.MuJoCoARService"),
                method: "UpdatePoses"
            )
        }
        /// Namespace for "StreamHandTracking" metadata.
        public enum StreamHandTracking {
            /// Request type for "StreamHandTracking".
            public typealias Input = MujocoAr_HandTrackingRequest
            /// Response type for "StreamHandTracking".
            public typealias Output = MujocoAr_HandTrackingUpdate
            /// Descriptor for "StreamHandTracking".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "mujoco_ar.MuJoCoARService"),
                method: "StreamHandTracking"
            )
        }
        /// Descriptors for all methods in the "mujoco_ar.MuJoCoARService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            SendUsdzUrl.descriptor,
            SendUsdzData.descriptor,
            SendUsdzDataChunked.descriptor,
            StreamPoses.descriptor,
            UpdatePoses.descriptor,
            StreamHandTracking.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "mujoco_ar.MuJoCoARService" service.
    public static let mujocoAr_MuJoCoARService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "mujoco_ar.MuJoCoARService")
}

// MARK: mujoco_ar.MuJoCoARService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MujocoAr_MuJoCoARService {
    /// Streaming variant of the service protocol for the "mujoco_ar.MuJoCoARService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Service definition for MuJoCo AR communication
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "SendUsdzUrl" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Send USDZ URL to VR device
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MujocoAr_UsdzUrlRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MujocoAr_UsdzUrlResponse` messages.
        func sendUsdzUrl(
            request: GRPCCore.StreamingServerRequest<MujocoAr_UsdzUrlRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_UsdzUrlResponse>

        /// Handle the "SendUsdzData" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Send USDZ file data directly
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MujocoAr_UsdzDataRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MujocoAr_UsdzDataResponse` messages.
        func sendUsdzData(
            request: GRPCCore.StreamingServerRequest<MujocoAr_UsdzDataRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_UsdzDataResponse>

        /// Handle the "SendUsdzDataChunked" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Send USDZ file data in chunks (for large files)
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MujocoAr_UsdzChunkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MujocoAr_UsdzDataResponse` messages.
        func sendUsdzDataChunked(
            request: GRPCCore.StreamingServerRequest<MujocoAr_UsdzChunkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_UsdzDataResponse>

        /// Handle the "StreamPoses" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Stream body pose updates to VR device
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MujocoAr_PoseUpdateRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MujocoAr_PoseUpdateResponse` messages.
        func streamPoses(
            request: GRPCCore.StreamingServerRequest<MujocoAr_PoseUpdateRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_PoseUpdateResponse>

        /// Handle the "UpdatePoses" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Single pose update (alternative to streaming)
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MujocoAr_PoseUpdateRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MujocoAr_PoseUpdateResponse` messages.
        func updatePoses(
            request: GRPCCore.StreamingServerRequest<MujocoAr_PoseUpdateRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_PoseUpdateResponse>

        /// Handle the "StreamHandTracking" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Stream hand tracking data from Vision Pro
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MujocoAr_HandTrackingRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MujocoAr_HandTrackingUpdate` messages.
        func streamHandTracking(
            request: GRPCCore.StreamingServerRequest<MujocoAr_HandTrackingRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_HandTrackingUpdate>
    }

    /// Service protocol for the "mujoco_ar.MuJoCoARService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Service definition for MuJoCo AR communication
    public protocol ServiceProtocol: MujocoAr_MuJoCoARService.StreamingServiceProtocol {
        /// Handle the "SendUsdzUrl" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Send USDZ URL to VR device
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MujocoAr_UsdzUrlRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `MujocoAr_UsdzUrlResponse` message.
        func sendUsdzUrl(
            request: GRPCCore.ServerRequest<MujocoAr_UsdzUrlRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<MujocoAr_UsdzUrlResponse>

        /// Handle the "SendUsdzData" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Send USDZ file data directly
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MujocoAr_UsdzDataRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `MujocoAr_UsdzDataResponse` message.
        func sendUsdzData(
            request: GRPCCore.ServerRequest<MujocoAr_UsdzDataRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<MujocoAr_UsdzDataResponse>

        /// Handle the "SendUsdzDataChunked" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Send USDZ file data in chunks (for large files)
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MujocoAr_UsdzChunkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `MujocoAr_UsdzDataResponse` message.
        func sendUsdzDataChunked(
            request: GRPCCore.StreamingServerRequest<MujocoAr_UsdzChunkRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<MujocoAr_UsdzDataResponse>

        /// Handle the "StreamPoses" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Stream body pose updates to VR device
        ///
        /// - Parameters:
        ///   - request: A streaming request of `MujocoAr_PoseUpdateRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MujocoAr_PoseUpdateResponse` messages.
        func streamPoses(
            request: GRPCCore.StreamingServerRequest<MujocoAr_PoseUpdateRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_PoseUpdateResponse>

        /// Handle the "UpdatePoses" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Single pose update (alternative to streaming)
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MujocoAr_PoseUpdateRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `MujocoAr_PoseUpdateResponse` message.
        func updatePoses(
            request: GRPCCore.ServerRequest<MujocoAr_PoseUpdateRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<MujocoAr_PoseUpdateResponse>

        /// Handle the "StreamHandTracking" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Stream hand tracking data from Vision Pro
        ///
        /// - Parameters:
        ///   - request: A request containing a single `MujocoAr_HandTrackingRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `MujocoAr_HandTrackingUpdate` messages.
        func streamHandTracking(
            request: GRPCCore.ServerRequest<MujocoAr_HandTrackingRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_HandTrackingUpdate>
    }

    /// Simple service protocol for the "mujoco_ar.MuJoCoARService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > Service definition for MuJoCo AR communication
    public protocol SimpleServiceProtocol: MujocoAr_MuJoCoARService.ServiceProtocol {
        /// Handle the "SendUsdzUrl" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Send USDZ URL to VR device
        ///
        /// - Parameters:
        ///   - request: A `MujocoAr_UsdzUrlRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `MujocoAr_UsdzUrlResponse` to respond with.
        func sendUsdzUrl(
            request: MujocoAr_UsdzUrlRequest,
            context: GRPCCore.ServerContext
        ) async throws -> MujocoAr_UsdzUrlResponse

        /// Handle the "SendUsdzData" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Send USDZ file data directly
        ///
        /// - Parameters:
        ///   - request: A `MujocoAr_UsdzDataRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `MujocoAr_UsdzDataResponse` to respond with.
        func sendUsdzData(
            request: MujocoAr_UsdzDataRequest,
            context: GRPCCore.ServerContext
        ) async throws -> MujocoAr_UsdzDataResponse

        /// Handle the "SendUsdzDataChunked" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Send USDZ file data in chunks (for large files)
        ///
        /// - Parameters:
        ///   - request: A stream of `MujocoAr_UsdzChunkRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `MujocoAr_UsdzDataResponse` to respond with.
        func sendUsdzDataChunked(
            request: GRPCCore.RPCAsyncSequence<MujocoAr_UsdzChunkRequest, any Swift.Error>,
            context: GRPCCore.ServerContext
        ) async throws -> MujocoAr_UsdzDataResponse

        /// Handle the "StreamPoses" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Stream body pose updates to VR device
        ///
        /// - Parameters:
        ///   - request: A stream of `MujocoAr_PoseUpdateRequest` messages.
        ///   - response: A response stream of `MujocoAr_PoseUpdateResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func streamPoses(
            request: GRPCCore.RPCAsyncSequence<MujocoAr_PoseUpdateRequest, any Swift.Error>,
            response: GRPCCore.RPCWriter<MujocoAr_PoseUpdateResponse>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "UpdatePoses" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Single pose update (alternative to streaming)
        ///
        /// - Parameters:
        ///   - request: A `MujocoAr_PoseUpdateRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `MujocoAr_PoseUpdateResponse` to respond with.
        func updatePoses(
            request: MujocoAr_PoseUpdateRequest,
            context: GRPCCore.ServerContext
        ) async throws -> MujocoAr_PoseUpdateResponse

        /// Handle the "StreamHandTracking" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > Stream hand tracking data from Vision Pro
        ///
        /// - Parameters:
        ///   - request: A `MujocoAr_HandTrackingRequest` message.
        ///   - response: A response stream of `MujocoAr_HandTrackingUpdate` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func streamHandTracking(
            request: MujocoAr_HandTrackingRequest,
            response: GRPCCore.RPCWriter<MujocoAr_HandTrackingUpdate>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MujocoAr_MuJoCoARService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: MujocoAr_MuJoCoARService.Method.SendUsdzUrl.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MujocoAr_UsdzUrlRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MujocoAr_UsdzUrlResponse>(),
            handler: { request, context in
                try await self.sendUsdzUrl(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MujocoAr_MuJoCoARService.Method.SendUsdzData.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MujocoAr_UsdzDataRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MujocoAr_UsdzDataResponse>(),
            handler: { request, context in
                try await self.sendUsdzData(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MujocoAr_MuJoCoARService.Method.SendUsdzDataChunked.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MujocoAr_UsdzChunkRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MujocoAr_UsdzDataResponse>(),
            handler: { request, context in
                try await self.sendUsdzDataChunked(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MujocoAr_MuJoCoARService.Method.StreamPoses.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MujocoAr_PoseUpdateRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MujocoAr_PoseUpdateResponse>(),
            handler: { request, context in
                try await self.streamPoses(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MujocoAr_MuJoCoARService.Method.UpdatePoses.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MujocoAr_PoseUpdateRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MujocoAr_PoseUpdateResponse>(),
            handler: { request, context in
                try await self.updatePoses(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: MujocoAr_MuJoCoARService.Method.StreamHandTracking.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<MujocoAr_HandTrackingRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<MujocoAr_HandTrackingUpdate>(),
            handler: { request, context in
                try await self.streamHandTracking(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MujocoAr_MuJoCoARService.ServiceProtocol {
    public func sendUsdzUrl(
        request: GRPCCore.StreamingServerRequest<MujocoAr_UsdzUrlRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_UsdzUrlResponse> {
        let response = try await self.sendUsdzUrl(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func sendUsdzData(
        request: GRPCCore.StreamingServerRequest<MujocoAr_UsdzDataRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_UsdzDataResponse> {
        let response = try await self.sendUsdzData(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func sendUsdzDataChunked(
        request: GRPCCore.StreamingServerRequest<MujocoAr_UsdzChunkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_UsdzDataResponse> {
        let response = try await self.sendUsdzDataChunked(
            request: request,
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func updatePoses(
        request: GRPCCore.StreamingServerRequest<MujocoAr_PoseUpdateRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_PoseUpdateResponse> {
        let response = try await self.updatePoses(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func streamHandTracking(
        request: GRPCCore.StreamingServerRequest<MujocoAr_HandTrackingRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_HandTrackingUpdate> {
        let response = try await self.streamHandTracking(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension MujocoAr_MuJoCoARService.SimpleServiceProtocol {
    public func sendUsdzUrl(
        request: GRPCCore.ServerRequest<MujocoAr_UsdzUrlRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<MujocoAr_UsdzUrlResponse> {
        return GRPCCore.ServerResponse<MujocoAr_UsdzUrlResponse>(
            message: try await self.sendUsdzUrl(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func sendUsdzData(
        request: GRPCCore.ServerRequest<MujocoAr_UsdzDataRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<MujocoAr_UsdzDataResponse> {
        return GRPCCore.ServerResponse<MujocoAr_UsdzDataResponse>(
            message: try await self.sendUsdzData(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func sendUsdzDataChunked(
        request: GRPCCore.StreamingServerRequest<MujocoAr_UsdzChunkRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<MujocoAr_UsdzDataResponse> {
        return GRPCCore.ServerResponse<MujocoAr_UsdzDataResponse>(
            message: try await self.sendUsdzDataChunked(
                request: request.messages,
                context: context
            ),
            metadata: [:]
        )
    }

    public func streamPoses(
        request: GRPCCore.StreamingServerRequest<MujocoAr_PoseUpdateRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_PoseUpdateResponse> {
        return GRPCCore.StreamingServerResponse<MujocoAr_PoseUpdateResponse>(
            metadata: [:],
            producer: { writer in
                try await self.streamPoses(
                    request: request.messages,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    public func updatePoses(
        request: GRPCCore.ServerRequest<MujocoAr_PoseUpdateRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<MujocoAr_PoseUpdateResponse> {
        return GRPCCore.ServerResponse<MujocoAr_PoseUpdateResponse>(
            message: try await self.updatePoses(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func streamHandTracking(
        request: GRPCCore.ServerRequest<MujocoAr_HandTrackingRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<MujocoAr_HandTrackingUpdate> {
        return GRPCCore.StreamingServerResponse<MujocoAr_HandTrackingUpdate>(
            metadata: [:],
            producer: { writer in
                try await self.streamHandTracking(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}